version: '3.7'

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
    ports:
      - 5432:5432
  
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
